### ISSUE TITLE
Issue with empty value in form data 

### ISSUE THREAD

**Issue by safalsigdel** [ortexx/express-form-data#2]
when I select form-data option in postman without using key value pair then BadRequestError exception is thrown. The error is BadRequestError: stream ended unexpectedly.
How can I provide default value for formdata when initializing this package?

**Comment by ortexx** [comment]
Hey! I can't reproduce your issue. Could you send me the raw headers of your request and the handling code? But anyway, this library is just a wrapper for multiparty.

**Comment by safalsigdel** [comment]
Request Headers:
Content-Type: application/x-www-form-urlencoded
clientid: ee221492155478c9cf77fc227247b074c76be56e
clientsecret: c79dec034e23a73417e56a9fea22ca9045d022efd5a8ca4c120e2c1b1668
User-Agent: PostmanRuntime/7.23.0
Accept: */*
Cache-Control: no-cache
Postman-Token: fb2ed362-41d8-419c-aea9-17c889664bde
Host: localhost:5000
Accept-Encoding: gzip, deflate, br
Content-Length: 0
Connection: keep-alive

Handler code is

const options = {
    uploadDir: os.tmpdir(),
    autoClean: true
};
app.use(formData.parse(options));
app.use(formData.format());
app.use(formData.stream());
app.use(formData.union());

Response:
BadRequestError: stream ended unexpectedly
    at Form.<anonymous> (/home/project/Service/node_modules/multiparty/index.js:759:24)
    at Form.emit (events.js:215:7)
    at Form.EventEmitter.emit (domain.js:475:20)
    at finishMaybe (_stream_writable.js:656:14)
    at endWritable (_stream_writable.js:673:3)
    at Form.Writable.end (_stream_writable.js:604:5)
    at IncomingMessage.onend (_stream_readable.js:692:10)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

I have used postman for api testing. If I select formdata and doesn't provide any key value pair then this issue occurs.

**Comment by ortexx** [comment]
Look at the content-type of your request. It must be multipart/form-data. Choose form-data instead of x-www-form-urlencoded in the postman.

**Comment by safalsigdel** [comment]
I changed to multipart/form-data but it is not working

**Comment by ortexx** [comment]
What do you change exactly? You can't just change the content type, because this type requires some additional information (boundary and so on). You have to choose form-data option in the postman to let it do all necessary things. And, please look into http content types specification.
