### ISSUE TITLE
Can you give me file name in field req.file

### ISSUE THREAD

**Issue by tockzazazx5** [ortexx/express-form-data#3]
![image](https://user-images.githubusercontent.com/62012985/76302370-70112180-62f2-11ea-8e0f-848fe931d065.png)
there is no original file name

**Comment by ortexx** [comment]
And should not. Remove formData.stream() if you want to get an original multiparty object instead of the node stream.

**Comment by tockzazazx5** [comment]
Thank for reply and thank for answer sir. I'm new for javascript node.js.

ในวันที่ อ. 10 มี.ค. 2020 เวลา 19:35 Alexander Balasyan <
notifications@github.com> เขียนว่า:
