### ISSUE TITLE
req.files is empty on Node.js v14

### ISSUE THREAD

**Issue by Tchoupinax** [ortexx/express-form-data#4]
Hello,

I use your middleware with express. When i upgrade to Node.js v14, my file upload crashes. I logged `req.files` and it appears to be an empty object (`{}`).
When i downgrade to Node.js v13, upload continue to work.

I notice the breaking change. :)
Thank you for your work

**Comment by ortexx** [comment]
https://github.com/expressjs/connect-multiparty/issues/29
Will wait for the result.

**Comment by ortexx** [comment]
The core library has been updated. The connect-multiparty version hasn't been updated yet, but you can reinstall(remove and install) all the libraries and it will work well.
