### ISSUE TITLE
Cannot find module 'express-form-data' in docker

### ISSUE THREAD

**Issue by lucaspereirasouzat** [ortexx/express-form-data#7]
error after try use in docker with typescript

`import 'reflect-metadata';
import 'dotenv/config';

import express, { Request, Response, NextFunction } from 'express';
import 'express-async-errors';
import cors from 'cors';
import { errors } from 'celebrate';

import formData from 'express-form-data';
import routes from './routes';

import AppError from './errors/AppError';

const app = express();

app.use(cors());
app.use(express.json());
app.use(formData.parse());
// app.use(express.urlencoded({ extended: true }));
// app.use(express.urlencoded());
app.use(routes);

app.use(errors());

app.use((err: Error, req: Request, res: Response, _: NextFunction) => {
  if (err instanceof AppError) {
    res.status(err.statusCode).json({
      status: 'error',
      message: err.message,
    });
  }

  res.status(500).json({
    status: 'error',
    message: err.message, // 'Internal server error',
  });
});

app.listen(3333, () => {
  // eslint-disable-next-line no-console
  console.log('Server is up on port 3333!');
});
`

**Comment by ortexx** [comment]
Be sure that you have it installed. Check node_modules folder, package.json and so on.
